name: Build

on: push

jobs:

  tests:
    name: "local tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name : Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble